In [5]:
import numpy as np

# 1.Create

In [6]:
data = np.random.rand(2,3,4)
zeroes = np.zeros((2,2,2))
full = np.full((2,2,2), 7)
ones = np.ones((2,2,2))

In [7]:
data

array([[[0.45624253, 0.31823093, 0.52641118, 0.61874506],
        [0.35147174, 0.21171452, 0.92150869, 0.06587676],
        [0.21327781, 0.35569617, 0.19175104, 0.60752038]],

       [[0.76898546, 0.56827945, 0.30340118, 0.44773962],
        [0.83489029, 0.40836227, 0.36543685, 0.04605575],
        [0.884157  , 0.70443803, 0.78259841, 0.43264858]]])

In [8]:
zeroes

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [9]:
full

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

In [10]:
ones

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

# 2. Read

In [12]:
# Attributes
shape = data.shape
size = data.size
types = data.dtype


In [13]:
shape

(2, 3, 4)

In [14]:
size

24

In [15]:
types

dtype('float64')

In [16]:
# Slicing
arr = data[0]
slicer = data[0][0:2]
reverse = data[-1]
singleval = data[0][0][0]

In [17]:
arr

array([[0.45624253, 0.31823093, 0.52641118, 0.61874506],
       [0.35147174, 0.21171452, 0.92150869, 0.06587676],
       [0.21327781, 0.35569617, 0.19175104, 0.60752038]])

In [18]:
slicer

array([[0.45624253, 0.31823093, 0.52641118, 0.61874506],
       [0.35147174, 0.21171452, 0.92150869, 0.06587676]])

In [19]:
reverse

array([[0.76898546, 0.56827945, 0.30340118, 0.44773962],
       [0.83489029, 0.40836227, 0.36543685, 0.04605575],
       [0.884157  , 0.70443803, 0.78259841, 0.43264858]])

In [20]:
singleval

0.45624252772883445

In [21]:
data

array([[[0.45624253, 0.31823093, 0.52641118, 0.61874506],
        [0.35147174, 0.21171452, 0.92150869, 0.06587676],
        [0.21327781, 0.35569617, 0.19175104, 0.60752038]],

       [[0.76898546, 0.56827945, 0.30340118, 0.44773962],
        [0.83489029, 0.40836227, 0.36543685, 0.04605575],
        [0.884157  , 0.70443803, 0.78259841, 0.43264858]]])

# 3. Update

In [22]:
list1 = np.random.rand(10) 
list2 = np.random.rand(10) 

In [24]:
list1

array([0.98666243, 0.33574888, 0.2836642 , 0.35469119, 0.28882924,
       0.42057162, 0.98241592, 0.9832969 , 0.99438996, 0.96308695])

In [25]:
list2

array([0.40937981, 0.79956988, 0.10866178, 0.54070308, 0.94844318,
       0.37623364, 0.33332504, 0.48565818, 0.29076904, 0.20697868])

In [26]:
# Basic Math
add = np.add(list1, list2)
sub = np.subtract(list1, list2)
div = np.divide(list1, list2)
mult = np.multiply(list1, list2)
dot = np.dot(list1, list2)

In [27]:
add

array([1.39604224, 1.13531875, 0.39232598, 0.89539427, 1.23727243,
       0.79680526, 1.31574097, 1.46895509, 1.28515899, 1.17006563])

In [28]:
sub

array([ 0.57728263, -0.463821  ,  0.17500242, -0.18601189, -0.65961394,
        0.04433799,  0.64909088,  0.49763872,  0.70362092,  0.75610828])

In [29]:
div

array([2.41013948, 0.41991186, 2.61052419, 0.65598145, 0.30452983,
       1.11784695, 2.94732109, 2.02466865, 3.41986189, 4.65307331])

In [30]:
mult

array([0.40391967, 0.26845469, 0.03082346, 0.19178262, 0.27393813,
       0.15823319, 0.32746383, 0.47754619, 0.28913781, 0.19933846])

In [31]:
dot

2.6206380460326484

In [32]:
# Stat Functions
sqrt = np.sqrt(25)
ab = np.abs(-2)
power = np.power(2,7)
log = np.log(25)
exp = np.exp([2,3])
mins = np.min(list1)
maxs = np.max(list1)

In [33]:
sqrt

5.0

In [34]:
ab

2

In [35]:
power

128

In [36]:
log

3.2188758248682006

In [37]:
exp

array([ 7.3890561 , 20.08553692])

In [38]:
mins

0.2836642010478625

In [39]:
maxs

0.9943899550260465

In [40]:
data

array([[[0.45624253, 0.31823093, 0.52641118, 0.61874506],
        [0.35147174, 0.21171452, 0.92150869, 0.06587676],
        [0.21327781, 0.35569617, 0.19175104, 0.60752038]],

       [[0.76898546, 0.56827945, 0.30340118, 0.44773962],
        [0.83489029, 0.40836227, 0.36543685, 0.04605575],
        [0.884157  , 0.70443803, 0.78259841, 0.43264858]]])

In [41]:
data[0][0][0] = 700
data

array([[[7.00000000e+02, 3.18230928e-01, 5.26411185e-01, 6.18745058e-01],
        [3.51471739e-01, 2.11714521e-01, 9.21508694e-01, 6.58767580e-02],
        [2.13277808e-01, 3.55696168e-01, 1.91751039e-01, 6.07520382e-01]],

       [[7.68985457e-01, 5.68279455e-01, 3.03401178e-01, 4.47739623e-01],
        [8.34890293e-01, 4.08362271e-01, 3.65436851e-01, 4.60557491e-02],
        [8.84157000e-01, 7.04438032e-01, 7.82598408e-01, 4.32648575e-01]]])

In [42]:
data.sort()
data

array([[[3.18230928e-01, 5.26411185e-01, 6.18745058e-01, 7.00000000e+02],
        [6.58767580e-02, 2.11714521e-01, 3.51471739e-01, 9.21508694e-01],
        [1.91751039e-01, 2.13277808e-01, 3.55696168e-01, 6.07520382e-01]],

       [[3.03401178e-01, 4.47739623e-01, 5.68279455e-01, 7.68985457e-01],
        [4.60557491e-02, 3.65436851e-01, 4.08362271e-01, 8.34890293e-01],
        [4.32648575e-01, 7.04438032e-01, 7.82598408e-01, 8.84157000e-01]]])

In [43]:
print(data.shape)
data = data.reshape((2,2,-1))
data.shape

(2, 3, 4)


(2, 2, 6)

In [44]:
zeroes = np.zeros((8))
print(zeroes)
zeroes = np.append(zeroes, [3,4])
print(zeroes)

[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 3. 4.]


In [45]:
zeroes = np.insert(zeroes, 2, 1)
print(zeroes)

[0. 0. 1. 0. 0. 0. 0. 0. 0. 3. 4.]


# 4. Delete

In [46]:
data

array([[[3.18230928e-01, 5.26411185e-01, 6.18745058e-01, 7.00000000e+02,
         6.58767580e-02, 2.11714521e-01],
        [3.51471739e-01, 9.21508694e-01, 1.91751039e-01, 2.13277808e-01,
         3.55696168e-01, 6.07520382e-01]],

       [[3.03401178e-01, 4.47739623e-01, 5.68279455e-01, 7.68985457e-01,
         4.60557491e-02, 3.65436851e-01],
        [4.08362271e-01, 8.34890293e-01, 4.32648575e-01, 7.04438032e-01,
         7.82598408e-01, 8.84157000e-01]]])

In [47]:
np.delete(data, 0, axis=1)

array([[[0.35147174, 0.92150869, 0.19175104, 0.21327781, 0.35569617,
         0.60752038]],

       [[0.40836227, 0.83489029, 0.43264858, 0.70443803, 0.78259841,
         0.884157  ]]])

In [48]:
np.save("new array", data)

In [49]:
test = np.load("new array.npy")


In [50]:
test

array([[[3.18230928e-01, 5.26411185e-01, 6.18745058e-01, 7.00000000e+02,
         6.58767580e-02, 2.11714521e-01],
        [3.51471739e-01, 9.21508694e-01, 1.91751039e-01, 2.13277808e-01,
         3.55696168e-01, 6.07520382e-01]],

       [[3.03401178e-01, 4.47739623e-01, 5.68279455e-01, 7.68985457e-01,
         4.60557491e-02, 3.65436851e-01],
        [4.08362271e-01, 8.34890293e-01, 4.32648575e-01, 7.04438032e-01,
         7.82598408e-01, 8.84157000e-01]]])